version: '3.8'
services:
  sburk:
    image: webdevops/php-nginx:7.2
    container_name: sburk
    working_dir: /app
    restart: always
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ${PWD}/src:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    networks:
      - sburk_vlan

  mysql:
    image: mysql:8.0.25
    container_name: mysql
    restart: on-failure
    volumes:
      - ${PWD}/data:/app:rw
      - sburk_data_mysql:/var/lib/mysql
    working_dir: /app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PWD}
    ports:
      - "3306:3306"
    networks:
      - sburk_vlan

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - sburk_vlan

networks:
  sburk_vlan:

volumes:
  sburk_data_mysql: